// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package sqlc

import (
	"context"
)

const getBudgetsForMonth = `-- name: GetBudgetsForMonth :many
SELECT
    c.name AS category_name,
    c.normalized_key AS category_key,
    b.month AS month,
    b.monthly_limit_minor AS monthly_limit_minor,
    COALESCE((
        SELECT SUM(amount_minor)
        FROM transactions t
        WHERE t.category_id = b.category_id
          AND t.type = 'expense'
          AND substr(t.date, 1, 7) = b.month
    ), 0) AS spent_month_to_date_minor
FROM budgets b
JOIN categories c ON c.id = b.category_id
WHERE b.month = ?
ORDER BY c.name COLLATE NOCASE ASC
`

type GetBudgetsForMonthRow struct {
	CategoryName          string      `json:"category_name"`
	CategoryKey           string      `json:"category_key"`
	Month                 string      `json:"month"`
	MonthlyLimitMinor     int64       `json:"monthly_limit_minor"`
	SpentMonthToDateMinor interface{} `json:"spent_month_to_date_minor"`
}

func (q *Queries) GetBudgetsForMonth(ctx context.Context, month string) ([]GetBudgetsForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getBudgetsForMonth, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBudgetsForMonthRow{}
	for rows.Next() {
		var i GetBudgetsForMonthRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.CategoryKey,
			&i.Month,
			&i.MonthlyLimitMinor,
			&i.SpentMonthToDateMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO budgets (category_id, month, monthly_limit_minor, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(category_id, month) DO UPDATE SET
    monthly_limit_minor = excluded.monthly_limit_minor,
    updated_at = datetime('now')
`

type UpsertBudgetParams struct {
	CategoryID        int64  `json:"category_id"`
	Month             string `json:"month"`
	MonthlyLimitMinor int64  `json:"monthly_limit_minor"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, upsertBudget, arg.CategoryID, arg.Month, arg.MonthlyLimitMinor)
	return err
}
