// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlc

import (
	"context"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (name, normalized_key, description)
VALUES (?, ?, ?)
`

type CreateCategoryParams struct {
	Name          string  `json:"name"`
	NormalizedKey string  `json:"normalized_key"`
	Description   *string `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory, arg.Name, arg.NormalizedKey, arg.Description)
	return err
}

const getCategoryByNormalizedKey = `-- name: GetCategoryByNormalizedKey :one
SELECT id, name, normalized_key, description, created_at
FROM categories
WHERE normalized_key = ?
`

func (q *Queries) GetCategoryByNormalizedKey(ctx context.Context, normalizedKey string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByNormalizedKey, normalizedKey)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, normalized_key, description, created_at
FROM categories
ORDER BY name COLLATE NOCASE ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedKey,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
