// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: initial_balance.sql

package sqlc

import (
	"context"
)

const getInitialBalance = `-- name: GetInitialBalance :one
SELECT id, initial_balance_minor, currency_code, initialized_at
FROM initial_balance
WHERE id = 1
`

func (q *Queries) GetInitialBalance(ctx context.Context) (InitialBalance, error) {
	row := q.db.QueryRowContext(ctx, getInitialBalance)
	var i InitialBalance
	err := row.Scan(
		&i.ID,
		&i.InitialBalanceMinor,
		&i.CurrencyCode,
		&i.InitializedAt,
	)
	return i, err
}

const upsertInitialBalance = `-- name: UpsertInitialBalance :one
INSERT INTO initial_balance (id, initial_balance_minor, currency_code, initialized_at)
VALUES (1, ?, ?, datetime('now'))
ON CONFLICT(id) DO UPDATE SET
    initial_balance_minor = excluded.initial_balance_minor,
    currency_code = excluded.currency_code,
    initialized_at = datetime('now')
RETURNING id, initial_balance_minor, currency_code, initialized_at
`

type UpsertInitialBalanceParams struct {
	InitialBalanceMinor int64  `json:"initial_balance_minor"`
	CurrencyCode        string `json:"currency_code"`
}

func (q *Queries) UpsertInitialBalance(ctx context.Context, arg UpsertInitialBalanceParams) (InitialBalance, error) {
	row := q.db.QueryRowContext(ctx, upsertInitialBalance, arg.InitialBalanceMinor, arg.CurrencyCode)
	var i InitialBalance
	err := row.Scan(
		&i.ID,
		&i.InitialBalanceMinor,
		&i.CurrencyCode,
		&i.InitializedAt,
	)
	return i, err
}
