// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Category struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	NormalizedKey string  `json:"normalized_key"`
	Description   *string `json:"description"`
	CreatedAt     string  `json:"created_at"`
}

type InitialBalance struct {
	ID                  int64  `json:"id"`
	InitialBalanceMinor int64  `json:"initial_balance_minor"`
	CurrencyCode        string `json:"currency_code"`
	InitializedAt       string `json:"initialized_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Transaction struct {
	ID                   string  `json:"id"`
	Type                 string  `json:"type"`
	AmountMinor          int64   `json:"amount_minor"`
	CurrencyCode         string  `json:"currency_code"`
	CategoryID           int64   `json:"category_id"`
	CategoryNameSnapshot string  `json:"category_name_snapshot"`
	Date                 string  `json:"date"`
	Description          *string `json:"description"`
	CreatedAt            string  `json:"created_at"`
}
