// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package sqlc

import (
	"context"
)

const getAnalyticsConsent = `-- name: GetAnalyticsConsent :one
SELECT id, analytics_opt_in
FROM analytics_consent
WHERE id = 1
`

func (q *Queries) GetAnalyticsConsent(ctx context.Context) (AnalyticsConsent, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticsConsent)
	var i AnalyticsConsent
	err := row.Scan(&i.ID, &i.AnalyticsOptIn)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value
FROM settings
WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i Setting
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const setAnalyticsConsent = `-- name: SetAnalyticsConsent :exec
INSERT INTO analytics_consent (id, analytics_opt_in)
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET analytics_opt_in = excluded.analytics_opt_in
`

func (q *Queries) SetAnalyticsConsent(ctx context.Context, analyticsOptIn int64) error {
	_, err := q.db.ExecContext(ctx, setAnalyticsConsent, analyticsOptIn)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
