// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package sqlc

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (id, type, amount_minor, currency_code, category_id, category_name_snapshot, date, description)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	ID                   string  `json:"id"`
	Type                 string  `json:"type"`
	AmountMinor          int64   `json:"amount_minor"`
	CurrencyCode         string  `json:"currency_code"`
	CategoryID           int64   `json:"category_id"`
	CategoryNameSnapshot string  `json:"category_name_snapshot"`
	Date                 string  `json:"date"`
	Description          *string `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.ID,
		arg.Type,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.CategoryID,
		arg.CategoryNameSnapshot,
		arg.Date,
		arg.Description,
	)
	return err
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.type, t.amount_minor, t.currency_code, t.category_id, t.category_name_snapshot, t.date, t.description, t.created_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE (?1 IS NULL OR c.normalized_key = ?1)
ORDER BY t.date DESC, t.created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListTransactionsParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AmountMinor,
			&i.CurrencyCode,
			&i.CategoryID,
			&i.CategoryNameSnapshot,
			&i.Date,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCumulativeTotalsUpToDate = `-- name: SumCumulativeTotalsUpToDate :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount_minor ELSE 0 END), 0) AS income_total_minor,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_minor ELSE 0 END), 0) AS expense_total_minor
FROM transactions
WHERE date <= ?
`

type SumCumulativeTotalsUpToDateRow struct {
	IncomeTotalMinor  interface{} `json:"income_total_minor"`
	ExpenseTotalMinor interface{} `json:"expense_total_minor"`
}

func (q *Queries) SumCumulativeTotalsUpToDate(ctx context.Context, date string) (SumCumulativeTotalsUpToDateRow, error) {
	row := q.db.QueryRowContext(ctx, sumCumulativeTotalsUpToDate, date)
	var i SumCumulativeTotalsUpToDateRow
	err := row.Scan(&i.IncomeTotalMinor, &i.ExpenseTotalMinor)
	return i, err
}

const sumTransactionTotalsForDay = `-- name: SumTransactionTotalsForDay :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount_minor ELSE 0 END), 0) AS income_total_minor,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_minor ELSE 0 END), 0) AS expense_total_minor
FROM transactions
WHERE date = ?
`

type SumTransactionTotalsForDayRow struct {
	IncomeTotalMinor  interface{} `json:"income_total_minor"`
	ExpenseTotalMinor interface{} `json:"expense_total_minor"`
}

func (q *Queries) SumTransactionTotalsForDay(ctx context.Context, date string) (SumTransactionTotalsForDayRow, error) {
	row := q.db.QueryRowContext(ctx, sumTransactionTotalsForDay, date)
	var i SumTransactionTotalsForDayRow
	err := row.Scan(&i.IncomeTotalMinor, &i.ExpenseTotalMinor)
	return i, err
}

const sumTransactionTotalsForMonth = `-- name: SumTransactionTotalsForMonth :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount_minor ELSE 0 END), 0) AS income_total_minor,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_minor ELSE 0 END), 0) AS expense_total_minor
FROM transactions
WHERE substr(date, 1, 7) = ?
`

type SumTransactionTotalsForMonthRow struct {
	IncomeTotalMinor  interface{} `json:"income_total_minor"`
	ExpenseTotalMinor interface{} `json:"expense_total_minor"`
}

func (q *Queries) SumTransactionTotalsForMonth(ctx context.Context, date string) (SumTransactionTotalsForMonthRow, error) {
	row := q.db.QueryRowContext(ctx, sumTransactionTotalsForMonth, date)
	var i SumTransactionTotalsForMonthRow
	err := row.Scan(&i.IncomeTotalMinor, &i.ExpenseTotalMinor)
	return i, err
}

const topCategoriesForMonth = `-- name: TopCategoriesForMonth :many
SELECT
    c.name AS category_name,
    c.normalized_key AS category_key,
    COALESCE(SUM(t.amount_minor), 0) AS amount_minor
FROM categories c
LEFT JOIN transactions t ON t.category_id = c.id AND t.type = 'expense' AND substr(t.date, 1, 7) = ?
GROUP BY c.id
HAVING SUM(t.amount_minor) > 0
ORDER BY amount_minor DESC, category_key ASC
`

type TopCategoriesForMonthRow struct {
	CategoryName string      `json:"category_name"`
	CategoryKey  string      `json:"category_key"`
	AmountMinor  interface{} `json:"amount_minor"`
}

func (q *Queries) TopCategoriesForMonth(ctx context.Context, date string) ([]TopCategoriesForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, topCategoriesForMonth, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopCategoriesForMonthRow{}
	for rows.Next() {
		var i TopCategoriesForMonthRow
		if err := rows.Scan(&i.CategoryName, &i.CategoryKey, &i.AmountMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
